### ISSUE TITLE
Running the Speechlet sample 

### ISSUE THREAD

**Issue by owlstack** [AreYouFreeBusy/AlexaSkillsKit.NET#14]
Hi, 

I'm trying to run the Speeclet sample but I am wondering, how can I test this with Alexa with this running locally (localhost with port) on my machine?

**Comment by stefann42** [comment]
Hi, have you read https://freebusy.io/blog/getting-started-with-alexa-app-development-for-amazon-echo-using-dot-net as indicated in the How To Use instructions in the README?

**Comment by owlstack** [comment]
Oh I see sorry. So, I should be listening on port 443: https://localhost:443/. 

On this note "If you're working in a small office or at home this means configuring your broadband modem to send traffic coming in on 443 to your dev machine." How do I do that? Just google set traffic on modem to 443 and I should find how to? 

Also, just to confirm, the above means I don't need to deploy to a web server. What if I end up hosting the sample on a web server, do I have to set up the above still? 

Thanks!

**Comment by bgarr33434** [comment]
Stefann, is there a step through video?  I have my environment set up, but now, I don't know what comes next.  I believe I need to create a webservice from the sample code?

**Comment by stefann42** [comment]
No instructional video, sorry. Start by reading the Amazon Alexa Skills Kit docs https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/overviews/understanding-custom-skills
