### ISSUE TITLE
The remote endpoint could not be called

### ISSUE THREAD

**Issue by Sanjeev143** [AreYouFreeBusy/AlexaSkillsKit.NET#15]
Hi @stefann42 thanks for the Lib. I just setup and published on the server but got the error below : 
_**The remote endpoint could not be called, or the response it returned was invalid**_
can you tell me why this happened, i have set the interaction model with - JSon
#14 Intent Schema-

`{
  "intents": [
    {
      "intent": "MyNameIsIntent",
      "slots": [
        {
          "name": "Name",
          "type": "LITERAL"
        }
      ]
    },
    {
      "intent": "WhatsMyNameIntent",
      "slots": []
    }
  ]
}`
# Sample Utterances

`MyNameIsIntent  my name is {john|Name}
MyNameIsIntent  my name is {sam brown|Name}
WhatsMyNameIntent whats my name
WhatsMyNameIntent what is my name
WhatsMyNameIntent say my name
WhatsMyNameIntent tell me my name
WhatsMyNameIntent tell me what my name is`
# Service Response

_**The remote endpoint could not be called, or the response it returned was invalid.**_
Do you have any idea why this happened ?

Thanks.

**Comment by chanan** [comment]
Hi, I have the same issue.

I get this when trying to test from the alexa developer page. If I take the resulting JSON that Amazon created for me and post it from Fiddler the result I get is:
```
HTTP/1.1 400 NoSignatureHeader, NoCertHeader, InvalidTimestamp
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 0
Expires: -1
Server: Microsoft-IIS/8.0
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Set-Cookie: ARRAffinity=9fa4c19acca1efb5e3249ffd618a5c2f0fd97fec0415c7247d77b5db8b98c453;Path=/;Domain=talky20161212103236.azurewebsites.net
Date: Fri, 23 Dec 2016 00:18:42 GMT
```

Is it possible that Amazon changed the API but the .net library hasn't been updated yet?

**Comment by jaddie** [comment]
It looks like this project is sadly outdated to the point of not working properly anymore as I am getting the same problem, if you grab the override at the bottom of the readme & apply it to your speechlet and simply return true (you could add your own validation, as it should be checking VS the application Id sent through) then it will work, currently playing battle with the onsessionstarted async items doing stupid things.

**Comment by jaddie** [comment]
I've been working on this since I posted that message & have a working setup. If you are creating your own self signed cert etc, make sure you have followed their instructions to generate it, there needs to be an alternate name set in the cert which matches your https url otherwise it fails.

Also if you are using the async methods, you must await the return value, do not try to execute it using .Result as it will fail on this!

**Comment by stefann42** [comment]
Thanks @jaddie for the additional details, glad you were able to resolve the issue. FWIW, we have production skills running with this library of which one passed certification today, so the library is certainly current.

In general, the error message "The remote endpoint could not be called" indicates a problem with the endpoint _prior_ to the flow reaching the library or skill code (like a TCP connection or SSL handshake not being able to be established).

@chanan The reason you are getting the 400 response when manually calling your endpoint from Fiddler is because you are not including the request signature

**Comment by chanan** [comment]
Hi @stefann42 Yes I see your point, but the original problem is that it cant be called from the Amazon test page. I am not using self signed cert, I have the sample deployed to Azure.

The code itself it pretty much the code from the sample. So I am not using async methods (although want to)

**Comment by chanan** [comment]
Do sites hosted on Azure using the default Cert that MS provides not work with Alexa maybe?

**Comment by jaddie** [comment]
Nope, they work perfectly just having the SSL setting to the subdomain setting instead. I was having issues getting it to respond and work before & threw it on a free azure web app  & had it working in seconds.

What does the Alexa app show? It should provide more detailed output about the error in there, maybe do as I did & add log4net to your project and start spitting out logging of all requests themselves so you can see what JSON Amazon is sending you?

**Comment by chanan** [comment]
Hi @jaddie,

Alexa just returns "The remote endpoint could not be called, or the response it returned was invalid." which from what I understand means that Alexa didn't reach my code. I am just using the sample code inside of my own project in a free azure web app.

**Comment by chanan** [comment]
I tried one more thing, I opened the actual AlexaSkillsKit.Sample that is in this repo, whichout changing anything, I published it to Azure (https://alexaskillskitsample20161229011039.azurewebsites.net/alexa/sample-session/).

Using the developer page on amazon I send the launch request:

```
{
  "session": {
    "sessionId": "SessionId.ee00017d-acc1-4b9b-b025-66172d3acbf6",
    "application": {
      "applicationId": "amzn1.ask.skill.b13af50f-898f-4191-8080-45f6b83010bf"
    },
    "attributes": {},
    "user": {
      "userId": "amzn1.ask.account.AG2KVKINEUNBERWUBJWWVTKIM4M4TIZDN2N63PXS3CVY3OTL3XTVZ72ABTY2AOLXFSVDWJYCFHTTJMNPYTZD55LMEF4XJHEXSEWRARVW6AV6GCVGNHVDATYPN4U7IXYEMJDIZMASV5BWHE4NV42RVQ4YC6FTRK7NCO3NL4DKRD6Y5EY7HB56US3IMKMBKDCWB65YUAODFVSQP2Y"
    },
    "new": true
  },
  "request": {
    "type": "LaunchRequest",
    "requestId": "EdwRequestId.5370c885-fb0f-44c0-9c60-5bb1535f4454",
    "locale": "en-US",
    "timestamp": "2016-12-29T20:18:27Z"
  },
  "version": "1.0"
}
```

And the response is: The remote endpoint could not be called, or the response it returned was invalid.

**Comment by chanan** [comment]
UPDATE: According the Amazon Alexa doesn't work with azure free SSL:

https://forums.developer.amazon.com/questions/3475/alexa-and-free-site-on-azure-ssl-issue.html

Back to the drawing board...

**Comment by jaddie** [comment]
This is untrue, I am using an Azure Web App to run my own skill with it set to wildcard SSL on the Amazon controls for the skill. You simply need the option saying its part of a subdomain on a wildcard SSL cert and it works.

Is your code somewhere that I can view & test it for you and see if I can find what is wrong?

**Comment by jaddie** [comment]
Also, if you are running this on Azure and getting that error, you could swith the diagnostic logs on in Azure and be able to view the requests to the site which should show if Amazon's request is getting there.

Another option would be to download a program such as Postman, take the request that Amazon shows you the JSON for & tell Postman to make a POST request to the url with a raw body & paste in the JSON, this would at least eliminate any other silly SSL issues or similar from Amazon's side & you could see if you get an error back from your skill :)

**Comment by jaddie** [comment]
**Re: 400 error**

For this you simply need to override the OnRequestValidation method in your speechlet & return true immediately, this will stop the lib doing any validation and allow the requests to go ahead.

I haven't had chance to look into this side of things yet, but it didn't seem to work on my end either originally when testing using the Json sent by Alexa, however now you have reminded me I'll re-enable the validation and see what happens and get back to you :)

I had an issue with this as I mentioned, and from what I've seen the validation should be the using the application id for verification, so I need to check why the library was falling over on it (might have been other issues, so will re-test now I have things working)

**Re: SSL Cert**

You need to go into the Amazon developer section & look at the SSL certification settings for your skill in Alexa & change according to my screenshot 
![image](https://cloud.githubusercontent.com/assets/68933/21555810/758d35e4-ce13-11e6-9b7e-82235c620838.png)

No setting changes are required on Azure for this to start working, you should already be able to access your site on https in a web app.

**Comment by stefann42** [comment]
side note @jaddie: FYI, the library doesn't currently implement automatic validation of the Application Id (it would require deciding on a way for the developer to put their Application Id in the config file or perhaps supply it as a parameter). For now if you want that check you need implement it in your skill.

**Comment by chanan** [comment]
@jaddie Thanks! I foolishly had it the config set to: "My development endpoint has a certificate from a trusted certificate authority" by mistake!

**Comment by kyleparker** [comment]
I too am running into these same issues. I am using a paid Azure app service plan (through my employer), the SSL option for "my development endpoint is a sub-domain", and have included the override for `OnRequestValidation`. Still hitting this error:

> There was an error calling the remote endpoint, which returned HTTP 500 : Internal Server Error" error during my testing on the Alexa/Amazon portal.

I did not make any changes to the sample project, just downloaded the source today (1/20/17), and published to Azure.

[https://test-alexaskills.azurewebsites.net/alexa/sample-session](https://test-alexaskills.azurewebsites.net/alexa/sample-session) 

Any suggestions would be greatly appreciated!

**Comment by fleekdeveloper** [comment]
Hi @stefann42 ,
I started using your library and works fine. I use it with Azure as in the previous cases. I wanted to update the NewtonSoft.Json to the latest version and stopped working due to errors on the response. 
Alexa would says that "The remote endpoint could not be called..." but I found the real error cause.

I am debugging my azure app and I noticed that it fails when trying to serialize the object for the SpeechletResponseEnvelop. 

//return JsonConvert.SerializeObject(this, SerializerSettings);

The error is about a StackOverflowException when attempting to serialize the object. Have you attempted to use the later NewtonSoft.Json version? if, so do you have any suggestions when using this newer version?

Thank you in advance

**Comment by stefann42** [comment]
@fleekdeveloper Please open a new issue so we can track your specific problem. Most likely you have circular references in the object that needs to be serialized. You can read about this: https://www.bing.com/search?q=json.net+prevent+circular+reference

**Comment by stefann42** [comment]
Closing this issue because it's not an actual issue with the library but rather operational challenges in configuring a skill endpoint.
