### ISSUE TITLE
HTTP 405 : Method Not Allowed

### ISSUE THREAD

**Issue by bellyflopp** [AreYouFreeBusy/AlexaSkillsKit.NET#16]
When using the Service Simulator in amazon's developer console portal I send a request and get the response:

_There was an error calling the remote endpoint, which returned HTTP 405 : Method Not Allowed_

Any ideas what is causing this to occur?

**Comment by stefann42** [comment]
That's an error you get when you haven't configured your Web API method to accept POST. See this question for common configuration errors http://stackoverflow.com/questions/15718741/405-method-not-allowed-web-api.
