### ISSUE TITLE
This is awesome so...thanks

### ISSUE THREAD

**Issue by TerribleDev** [AreYouFreeBusy/AlexaSkillsKit.NET#17]
Ok so I've made 3 skills already hosted in azure app service with this. Have to admit this is awesome, used it because I have a ton of stuff in azure and didn't really want to use aws lambda.

So thanks for making this....

**Comment by stefann42** [comment]
Glad to hear, thanks for your note. At some point I'd like to also look at Azure Functions to make sure this library can also work with with equivalent of AWS Lambda in Azure.
