### ISSUE TITLE
Required outbound calls?

### ISSUE THREAD

**Issue by cmeans** [AreYouFreeBusy/AlexaSkillsKit.NET#19]
Hi,

I've locally tested a AlexaSkillsKit.NET implementation and it's working fine.  I've now deployed it to a staging server (publicly accessible) but it's failing (from Amazon) with an HTTP 500.

I did initially have deployment issues:  I'd developed under .Net 4.6, but only 4.5.2 was available...should now be fixed.

I'm wondering if there's some internal authentication going on (or something) that requires an outbound call back to AWS.

All our hosted servers are in a very strict environment, and we have Egress Filters which will only allow approved out-bound traffic.  I'm seeing 3 calls to 54.231.120.42/443 right after I initiate the Alexa test...but our filters are blocking them.

Is this the likely reason for the HTTP 500?  Can you point me to where I can find the right list of IPs or DNS names to approve for outbound calls (that would be specific to an Alexa Skill)?

Given how often our sites are attacked from AWS hosted instances, we need to be very careful about what we open up to.

Thanks!

**Comment by stefann42** [comment]
Hi Chris, there can be many reasons that cause IIS/ASP.NET to responsd with HTTP Status Code 500. However, in this case, the fact that you completely block outbound traffic is most likely the causes. 

The library must verify the authenticity of incoming requests and to do so it needs to download a certificate off `s3.amazonaws.com` (the location was decided by the Alexa team and is outside our control). So the outbound requests to `54.231.120.42` (which is one of the many IPs backing S3 service) are to download that certificate. 

It's unfortunate that Alexa team didn't choose a less generic endpoint for hosting the validation certs (`s3.amazonaws.com` is used by so many services). You can open a thread on the forums and give them this feedback.
