### ISSUE TITLE
A number of bugs in the kit

### ISSUE THREAD

**Issue by oznetmaster** [AreYouFreeBusy/AlexaSkillsKit.NET#2]
The kit, as posted here has a number of bugs in the code.  Is there a newer version somewhere, because this one is not functional?

I have fixed three bugs so far, and am still working on it.

**Comment by stefann42** [comment]
This is the current and latest version of the library and it works in production for the FreeBusy Scheduling Buddy skill. Please submit pull requests with your bug fixes and happy to code review and accept into the project.

**Comment by stefann42** [comment]
It's possible you were hitting this bug if your skill was deriving from Speechlet rather than SpeechletAsync: https://github.com/AreYouFreeBusy/AlexaSkillsKit.NET/commit/aafc9eba7671a5363fa4dddcd2ed90d8456bf6f4
