### ISSUE TITLE
Amazon AWS Lex

### ISSUE THREAD

**Issue by StephenShamakian** [AreYouFreeBusy/AlexaSkillsKit.NET#21]
Will this work with the Amazon Lex Bot Framework?

More info: https://aws.amazon.com/lex/
Video Overview: https://www.youtube.com/watch?v=7uG9cuxNo5k

**Comment by stefann42** [comment]
The Amazon Lex Bot Framework is not a relevant technology for the Alexa Skills Kit because Alexa service handles NLP and mapping from speech to text and then from text to utterances and intents.
