### ISSUE TITLE
Account Linking

### ISSUE THREAD

**Issue by chmasi** [AreYouFreeBusy/AlexaSkillsKit.NET#22]
Hey Stefan
Thanks for this great library, I did 2 days ago my first step with it, and after some probing I was able to get it working :-)

Now I have a question, do you have a sample code how I can use account linking with your library? 

Thanks 
Martin

**Comment by tamhinsf** [comment]
My Visual Studio + Azure starter project which uses this package demonstrates how you can use Account Linking with the Microsoft Authentication Endpoint:

https://github.com/tamhinsf/Azure4Alexa/

You can follow the steps here to create a skill that makes use of Account Linking with Microsoft Outlook:

https://github.com/tamhinsf/Azure4Alexa/tree/master/Azure4Alexa/Outlook
