### ISSUE TITLE
Alexla custom skill - There was an error calling the remote endpoint, which returned HTTP 400

### ISSUE THREAD

**Issue by brianperera** [AreYouFreeBusy/AlexaSkillsKit.NET#25]
I'm new to Alexa and I have created a custom skill set and have hosted it on Azure cloud. When I try to test my service request using developer portal, I get the following error,

> There was an error calling the remote endpoint, which returned HTTP 400 : OK

Few things to note:

- 1. I have a trusted SSL certificate issued by GoDaddy (Only covers my main domain and not sub-domains)
- 2. I have Hosted my Alexa skill set endpoint in the main domain and NOT sub-domain. e.g. https://brandsmacker.com/api/Alexa/sample-session
- 3. For testing purposes when I try to send a request to the Alexa skill set end point through PostMan, it gives me a status called - 400 NoSignatureHeader, NoCertHeader

Appreciate if someone can help me to figure out the problem.

**Comment by stefann42** [comment]
Closing this issue because it's not an actual issue with the library but rather operational challenges in configuring a skill endpoint.
