### ISSUE TITLE
Add locale to Requests

### ISSUE THREAD

**Issue by nielsvoigt** [AreYouFreeBusy/AlexaSkillsKit.NET#26]
Hi, 

I noticed that the locale property is missing from the requests. 

The Java version has a commit for it, would it be possible to add this to the requests in AlexaSkillsKit.NET?

For comparison:
https://github.com/KayLerch/alexa-skills-kit-java/commit/7784d0f048dd810acec0a36b597a551d8eb26c32

Thank you for letting us use your hard work guys!

**Comment by stefann42** [comment]
Yes, we'll add this in the next release.

**Comment by nielsvoigt** [comment]
Great!

**Comment by tarig-sinada-schneider** [comment]
Hi, could we please have an update as to when this will be released. Much obliged.

**Comment by jejernig** [comment]
could you make a dev branch of that release? I have hacked together getting device information  but having issues with getting the consentToken

**Comment by ElvenMonky** [comment]
ConsentToken is now obsolete and should not be used. So Its support is not added to the library. Support of AccessToken was added in #53
