### ISSUE TITLE
want to go from launchRequest to accepting an intentRequest.

### ISSUE THREAD

**Issue by bgarr33434** [AreYouFreeBusy/AlexaSkillsKit.NET#28]
Im connecting Alexa to Cognitive Codes SILVIA conversational AI.  If I say "tell Silvia hello" it works great, SILVIA opens with a hello statement.  But if I just say "use SILVIA", of course, it goes to launchRequest.  structurally, I want it to execute intentRequest, not launchRequest.  the problem is that the json coming from Alexa is marked as launchRequest.

**Comment by stefann42** [comment]
Not an issue specific this library, so closing.
