### ISSUE TITLE
Add device info to Context object for new geo-location feature

### ISSUE THREAD

**Issue by amp64** [AreYouFreeBusy/AlexaSkillsKit.NET#30]
Once the AudioPlayer pull request is accepted we will get Context support, can you please add support for _device_ to it as well? (and apiEndpoint too).

**Comment by stefann42** [comment]
Yes, I'd like to implement support for the new location feature

**Comment by jejernig** [comment]
shameles bump

**Comment by ElvenMonky** [comment]
Fixed by #53
