### ISSUE TITLE
Sample code works with SessionResponse but not HttpResponseMessage

### ISSUE THREAD

**Issue by shuri1** [AreYouFreeBusy/AlexaSkillsKit.NET#32]
public HttpResponseMessage Post([FromBody] dynamic request)
{
    return new SessionResponse
    {
                version = "1.0",
                sessionAttributes = null,
                response = new AlexaResponse
                {
                    outputSpeech = new AlexaOutputSpeech
                    {
                        type = "PlainText",
                        text = $"The Price of {request} is 1"
                    },
                    shouldEndSession = true
                }
            };
        }

This works, and returns what I expect....

        [Route("alexa/getme")]
        [HttpGet]
        public HttpResponseMessage SampleSession2()
        {
            var speechlet = new CoinbaseSkillSpeechlet();
            return speechlet.GetResponse(Request);
        }

Returns an error message of There was an error calling the remote endpoint, which returned HTTP 500 : Internal Server Error 

I have the https crt set to "My development endpoint is a sub-domain of a domain that has a wildcard certificate from a certificate authority" and I am running this on azure

Like i said, the first one, not using the AlexaSkillKit works....this one, using ASK doesnt.

Any help would be appreciated

**Comment by amp64** [comment]
Without seeing the entirety of your code its impossible to say. Look at the exceptions you are getting on the server and debug them. I recommend adding a Test method to your Controller that calls into the same method, and debug that locally.

**Comment by shuri1** [comment]
Hi,

I literally copied the sample code, unchanged.  When I attach a debugger to the w3 process, I step through it, and everything is fine....but then it returns to amazon  i get the message "The remote endpoint could not be called, or the response it returned was invalid."

I have created a different example, like above which returns SessionResponse and doesnt use AlexaSkillsKit and it works fine....

I'm not sure why but the HttpResponseMessage seems to make alexa unhappy.  

My certs are most likely set up correctly as when alexa sends the json packet, my local machine receives it, so my certs seem in order and my firewall seems configured appropriately....any help would be appreciated.

**Comment by amp64** [comment]
If you are returning an http 500 (as originally reported) then something in your code is causing an uncaught exception. As you have a debugger connected, that should be somewhat obvious. If you have App Insights connected, that would also show it.

**Comment by shuri1** [comment]
This time I'm getting message "The remote endpoint could not be called, or the response it returned was invalid."

I can get all the way through to the return with out a single error.  It's only when it returns to alexa

**Comment by amp64** [comment]
FWIW here is my impl:

`        public async Task<HttpResponseMessage> Session()
        {
            var speechlet = new SessionSpeechlet();
            return await speechlet.GetResponseAsync(Request);
        }
`

**Comment by amp64** [comment]
Mine is marked as [HttpPost] not [HttpGet]

**Comment by shuri1** [comment]
I'm using the demo from github, literally unchanged....

I can try converting to async, although i would be surprised if that made a difference....

**Comment by stefann42** [comment]
Closing this issue because it's not an actual issue with the library but rather operational challenges in configuring a skill endpoint.
