### ISSUE TITLE
Our skill is failing at validating the signatures for incoming requests and is accepting requests with an empty signature URL

### ISSUE THREAD

**Issue by gorgi** [AreYouFreeBusy/AlexaSkillsKit.NET#33]
We are using this library for our custom Alexa skill, and we are very happy about how easy it was to develop the skill using it. Kudos to you guys!

However, the only thing that the Amazon certification team is failing us is the endpoint validation. This is the response we got from them:

> These are the tests where your skill's back-end server is responding with HTTP Code 200 (OK) when we would expect to receive with HTTP Code 400 (Bad Request):
> 
> - Empty signature
> - No signature header specified
> - Request signed with incorrect certificate
> - Request signed with invalid signature

We have made sure that the OnRequestValidation is returning false for invalid requests. So, my questions are:

1. Has Amazon changed anything in their test suite for which this library hasn't been updated?
2. How can we reproduce the tests that they are making, so we can fix the issue on our own?
3. They told us that 

> Please note, that skills hosted on AWS Lambda have these security checks managed by Amazon automatically.

so, we are thinking of making a Lambda function that will act as a proxy to our Alexa API. Will this be acceptable to Amazon team and are there any downsides (besides the obvious increase in response time and costs)? We have passed the deadline, so we have to move forward with this solution in couple of days, because we're running out of options.

Thanks!

**Comment by amp64** [comment]
My Skill that uses this library was recently approved by Amazon. I don't override OnRequestValidation at all, and have never had a problem in this area. I am hosting as an Azure Web API on an S1 Standard config. I would suggest taking closer a look at the requests you are getting from Amazon.

**Comment by stefann42** [comment]
Closing this issue because we don't have other reports of failing at validating the signatures with release v1.5.2 and later.
