### ISSUE TITLE
Please add support for Address Information

### ISSUE THREAD

**Issue by EgMan** [AreYouFreeBusy/AlexaSkillsKit.NET#36]
I need to be able to access the user's address, and Amazon only added support for this recently in April 2017. https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/device-address-api 

Namely, I need a way to access both device ID and consent Token in a launch request.
Please let me know if there's a way to do this because I can't find any such implementation in the project.

As stated, I need access, so please let me know if there is no implementation and no plans for implementation so I can migrate libraries.  

Thank you

**Comment by stefann42** [comment]
Hi @EgMan, I plan to add support for the device address API.

**Comment by EgMan** [comment]
That's great to hear.  Do you have an idea about the timeline of when this could be available? Or are you too busy to be able to say? Thanks

**Comment by ElvenMonky** [comment]
Just for note, you can easily derive your own class from Card like below:
`public class AskForPermissionsConsentCard : Card
    {
        public override string Type {
            get { return "AskForPermissionsConsent"; }
        }

        public virtual IEnumerable<string> Permissions {
            get;
            set;
        }
    }`
and provide it in the response.

**Comment by ElvenMonky** [comment]
Should be fixed by PR #53

**Comment by stefann42** [comment]
@EgMan This issue is resolved by release v1.6.0
