### ISSUE TITLE
Support for the Dialog interface

### ISSUE THREAD

**Issue by alindgren** [AreYouFreeBusy/AlexaSkillsKit.NET#39]
As far as I can tell, AlexaSkillsKit.NET does not support the [`Dialog` Interface](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/dialog-interface-reference).

**Comment by realares** [comment]
I don't like self-promotion, but you can try an inplemention of this in my fork: https://github.com/realares/Ra.AlexaSkillsKit.NET

**Comment by stefann42** [comment]
@realares You should submit pull requests and contribute to this library. Then you don't have to worry about self-promotion :).

**Comment by alindgren** [comment]
Thanks @realares - I'll check out your fork but a PR would be nice!

**Comment by ElvenMonky** [comment]
I've created PR #53 to add support of Directives in SpeechletResponse.

**Comment by ElvenMonky** [comment]
Fixed by #53
