### ISSUE TITLE
Reprompt

### ISSUE THREAD

**Issue by petersantiago** [AreYouFreeBusy/AlexaSkillsKit.NET#42]
This does not seem to be available?
Anyone have an example using this library?

Thanks

**Comment by ElvenMonky** [comment]
Well, the Reprompt object actually IS currently supported, and can be used like below:

```
public override SpeechletResponse OnIntent(IntentRequest intentRequest, Session session) {
    ... // Some intent handling code
    return new SpeechletResponse {
        ... // Other fields 
        Reprompt = new Reprompt {
            OutputSpeech = new PlainTextOutputSpeech("Your reprompt speech")
        }
    };
}
```

**Comment by ndbills** [comment]
I am unable to initialize a PlainTextOutputSpeech with a string in my code. Am I doing it wrong? I followed your example but I keep getting errors on PlainTextOutputSpeech saying no constructor with 1 argument exists. I am using 1.6.0.

`var response = BuildSpeechletResponse("Welcome", speechOutput, false);`
`response.Reprompt = new Reprompt { OutputSpeech = new PlainTextOutputSpeech("Your reprompt speech") };`

**Comment by stefann42** [comment]
@ndbills Try
```
response.Reprompt = new Reprompt { 
    OutputSpeech = new PlainTextOutputSpeech {
        Text = "Your reprompt speech" 
    }
};
```

**Comment by ElvenMonky** [comment]
Yep, sorry for that. Other option is:
```
response.Reprompt = new Reprompt { 
    OutputSpeech = (PlainTextOutputSpeech)"Your reprompt speech"
};
```

**Comment by ndbills** [comment]
Thank you both for the quick reply. This really helped a lot, and I seem to have things working 👍
