### ISSUE TITLE
Unique Identifiers and Resolutions

### ISSUE THREAD

**Issue by tobiratzberger** [AreYouFreeBusy/AlexaSkillsKit.NET#54]
It would be great if it's possible to get the Id of an Slot Value!

https://developer.amazon.com/de/docs/custom-skills/define-synonyms-and-ids-for-slot-type-values-entity-resolution.html#slot-value-synonyms-unique-identifiers-and-entity-resolution

**Comment by ElvenMonky** [comment]
Hi, I've added required changes to support slot resolutions to PR #53 currently being reviewed. I hope we will be able to release new library version with all the new features this year.

**Comment by ElvenMonky** [comment]
Fixed by #53
