### ISSUE TITLE
Display Interface Reference

### ISSUE THREAD

**Issue by tobiratzberger** [AreYouFreeBusy/AlexaSkillsKit.NET#55]
Would it be possible to include the Echo Show support?

https://developer.amazon.com/de/docs/custom-skills/display-interface-reference.html

**Comment by ElvenMonky** [comment]
This feature is being adressed in PR #52 currently being reviewed as part of PR #53. I believe, it will be present in next library release.

**Comment by psantiago1969** [comment]
Hi,

Wondering if you could provide c# example of using context to get the Display templateversion value ... is 1 if display is supported.  Trying using your new code and receive a null?  Thanks in advance, Peter

**Comment by ElvenMonky** [comment]
Fixed by #52

**Comment by stefann42** [comment]
@tobiratzberger release v1.6.0 addresses this issue
