### ISSUE TITLE
Seems in Testing, the Version is not sent making all calls fail

### ISSUE THREAD

**Issue by Jcouls29** [AreYouFreeBusy/AlexaSkillsKit.NET#6]
When using the Tester App through Amazon, it sends a request like so:

{
  "session": {
    "sessionId": "SessionId.*******************************************",
    "application": {
      "applicationId": "amzn1.echo-sdk-ams.app.*******************************************"
    },
    "user": {
      "userId": "amzn1.echo-sdk-account.*************************************************"
    },
    "new": true
  },
  "request": {
    "type": "IntentRequest",
    "requestId": "EdwRequestId.***********************************************",
    "timestamp": "2016-03-14T23:48:06Z",
    "intent": {
      "name": "MyBasicIntent",
      "slots": {
        "Name": {
          "name": "Name",
          "value": "john"
        }
      }
    }
  }
}

This does not have a version inside it, causing it to fail.  Has version been removed (or deprecated) on amazon's side?

**Comment by stefann42** [comment]
No, `version` is present in requests coming from the production Alexa service. It seems it's only missing from requests that originate with the Tester. We can make the check for the version field optional if we could understand from the Amazon Alexa team that this is an expected condition. I'll ask in the forums https://forums.developer.amazon.com/forums/category.jspa?categoryID=48 and please reach out to the team if you know of any other communication channels.

**Comment by Jcouls29** [comment]
I'm new to the community.  I'll see what I can figure out.  Thanks

**Comment by stefann42** [comment]
Hi, I made a change to accept requests that don't have the version field 
https://github.com/AreYouFreeBusy/AlexaSkillsKit.NET/commit/38a4491ccbfa10616c22c734d74905ea5d3a3d83 which is included in release 1.5.0.

That being said, I noticed that since you opened this issue the official test tool on https://developer.amazon.com was modified to also send the version field.
