### ISSUE TITLE
Awaiting null conditional operations

### ISSUE THREAD

**Issue by MattBecker** [AreYouFreeBusy/AlexaSkillsKit.NET#62]
SpeechletService.HandleStandardRequestAsync()
performs casting to all the interfaces to find the right one to call the request type handler.

but await (null)?.DoAsync() does not work
https://github.com/dotnet/roslyn/issues/7171

I just want to make sure it is not a problem in the way I am calling it, so am testing a fix now.

**Comment by ElvenMonky** [comment]
Thanks, man! Not sure, why I was under impression that Null propagation would work with await, while writing this code.

**Comment by ElvenMonky** [comment]
Fixed 5be461

**Comment by MattBecker** [comment]
Fixed - tested with 5be461d
Thanks @ElvenMonky
