### ISSUE TITLE
ProcessRequestAsync handles standard/extended backward

### ISSUE THREAD

**Issue by MattBecker** [AreYouFreeBusy/AlexaSkillsKit.NET#63]
SpeechletService.ProcessRequestAsync()
has a check for determining standard/extended, which appears to be backward.  I would expect this to be a 'not is' check:

            var response = (request is ExtendedSpeechletRequest) ?
                await HandleStandardRequestAsync(request, session, context) :
                await HandleExtendedRequestAsync(request as ExtendedSpeechletRequest, context);

**Comment by ElvenMonky** [comment]
Thanks @MattBecker! It looks like I need to write some functional tests to verify common use cases.

**Comment by MattBecker** [comment]
I just signed the CLA (after merging my other account).
I could not find any existing tests around this code path, otherwise I would have added one for this change.

**Comment by MattBecker** [comment]
Fixed - tested with 5be461d
Thanks @ElvenMonky 
That PR is now not needed
