### ISSUE TITLE
Updating NuGet Package

### ISSUE THREAD

**Issue by tobiratzberger** [AreYouFreeBusy/AlexaSkillsKit.NET#65]
Hello!

When is the next NuGet update planned to be?

Regards,
Tobi

**Comment by stefann42** [comment]
This week. I'm just doing some testing with the latests updates for our own skill. Thanks for your patience,

Stefan


On Jan 15, 2018, at 10:48 PM, Tobi Ratzberger <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello!

When is the next NuGet update planned to be?

Regards,
Tobi

**Comment by ElvenMonky** [comment]
Today I've tested multi-turn dialog interface of current library with functional tests for my skill. Tests showed no issues.

**Comment by stefann42** [comment]
@tobiratzberger I just published release v1.6.0 on NuGet. Let us know how it works for you. Thanks!
