### ISSUE TITLE
ExtendedSpeechletRequest doesn't include the session variable

### ISSUE THREAD

**Issue by thailandmatt** [AreYouFreeBusy/AlexaSkillsKit.NET#69]
Is there a reason that the handlers for ExtendedSpeechletRequest don't get passed the session object?  We have an echo show app and want to handle the point in the conversation where the user touches the screen, but don't have access to the session history.  The session is in the raw JSON request, and it looks like in your SpeechletSession.cs you have it, but aren't passing it to the ExtendedSpeechletRequest handler.

**Comment by ElvenMonky** [comment]
According to [documentation](https://developer.amazon.com/docs/custom-skills/request-and-response-json-reference.html#session-object):
> Standard request types (LaunchRequest, IntentRequest, and SessionEndedRequest) include the session object.
> Requests from interfaces such as AudioPlayer and PlaybackController are not sent in the context of a session, so they do not include the session object.
And some [more](https://developer.amazon.com/docs/custom-skills/request-and-response-json-reference.html#request-body-parameters):
> Note: The session is included for all standard requests, but it is not included for AudioPlayer, VideoApp, or PlaybackController requests.

Session history is non-standard library feature, which can only work for requests, that provide session information. For interface requests library temporary creates empty session object and adds item to session history to fulfill `sessionAttributes` in Response. But still:
> Session attributes are ignored if included on a response to an AudioPlayer or PlaybackController request.

Display and Dialog interfaces doesn't have their own request types.
[Skill events](https://developer.amazon.com/docs/smapi/skill-events-in-alexa-skills.html#skill-events-in-json-format) doesn't seem to include session object as well.
Only few of [List events](https://developer.amazon.com/docs/smapi/list-events-in-alexa-skills.html#list-events-json) include session object in example requests, but missing most of the required fields and without any meaningful description.

If you're trying to add support for `List events` I'm afraid currently you will have to modify and build library from source code. We are considering to follow Java Library implementation in v2.0, which gives request handlers access directly to SpeechletResponseEnvelope.
