### ISSUE TITLE
The skill responded with 500 HTTP status Code

### ISSUE THREAD

**Issue by smussani** [AreYouFreeBusy/AlexaSkillsKit.NET#7]
I get this error message as soon as I ask Echo for my skill. "There was a problem with the requested skill's response".  I see the following error on my Alexa App: The skill responded with 500 HTTP status Code

The error response is so fast that it seems like it is not even hitting my external web service end point.

please help
Sajjad

**Comment by stefann42** [comment]
Are you getting this response running the sample skill or your own skill? 

HTTP Status Code 500 is a "catch all" error code returned by IIS and ASP.NET Web API whenever there is an unhandled exception or incorrect configuration. Most likely it's unrelated to AlexaSkillsKit.NET and it's related to problems either in your own IIS configuration or in your skill's code.

**Comment by smussani** [comment]
it's my own skill.  What would be the best way to debug it?

**Comment by stefann42** [comment]
If it's a bug in your code you'll see it when you run in debug mode from Visual Studio (it will break on unhandled exceptions). You can learn more about troubleshooting techniques for ASP.NET Web API at http://www.asp.net/web-api/overview/error-handling and http://www.asp.net/web-api/overview/testing-and-debugging.

I'll close this issue because it's not a problem with AlexaSkillsKit.NET and unfortunately we don't have the resources to provide developer support for your own skills.

**Comment by smussani** [comment]
I just tested the sample skill and got the same exact response.  Could it be my end point?  I am hosting my end point at a shared hosting service.  It has an SSL cert from an authority that Amazon recognizes.  Is there anyway to tell if the end is not accessible to Amazon

**Comment by smussani** [comment]
I don't need dev support.. but thanks for pointing those site out.  I don't have any errors in my code. I might just be the end point

**Comment by stefann42** [comment]
Well, how are you testing your skill right now?

**Comment by smussani** [comment]
in my skill's settings, I have the end point pointing to my published code on the share hosting IIS server.  I have setup the interaction model and utterances for sample session and the skill is enabled for testing.  I enabled the skill on my Alexa App and then asked Alexa on my Echo: "Alexa Ask" + my skill name

**Comment by stefann42** [comment]
And how are you determining that the skill endpoint is returning 500?

**Comment by smussani** [comment]
that's what I am wondering.  As soon as I ask Alexa, I hear the message and the Alexa App shows a error card with 500 HTTP status code.

**Comment by stefann42** [comment]
My suspicion is that there's a problem with how the IIS is configured in your shared hosting environment or how Web.Api routes are mapped to. Use the techniques described in the tutorials. Good luck!

**Comment by smoore4moma** [comment]
A 500 error can be all sorts of things.  For example, I wanted to add images to a standard card, and it **seems** like you can do that like this:

            card.Image.SmallImageUrl = @"https://mydomain.com/small_img.jpg";
            card.Image.LargeImageUrl = @"https://mydomain.com/large_img.jpg";
 
But you will get an http status 500 error with no debugging information.  Instead, the Amazon documentation shows that Image is an object, not a string, and then it clicks that you need to add images to a standard card like this: 

            Image img = new Image();
            img.SmallImageUrl = @"https://mydomain.com/small_img.jpg";
            img.LargeImageUrl = @"https://mydomain.com/large_img.jpg";

            StandardCard card = new StandardCard();
            card.Title = "Title";
            card.Text = "Some text...";
            card.Image = img;

So I would look at things like the card, reprompt, etc.  Just FYI

Steve
