### ISSUE TITLE
How to use AskForPermissionsConsentCard

### ISSUE THREAD

**Issue by petersantiago** [AreYouFreeBusy/AlexaSkillsKit.NET#72]
Hi,

I have a skill that requires the users address.

**From the Amazon Site:**
Full address | Country and postal code
read::alexa:device:all:address 
read::alexa:device:all:address:country_and_postal_code

I created a reusable function, but need to understand how to implement the Consent Card.
Can you help?  Thank you!

private SpeechletResponse BuildSpeechletResponseSSML2(string title, string output, string outPutCard, bool shouldEndSession, string repromptText)
        {
            // Create the Simple card content.
            var consentCard = new AskForPermissionsConsentCard();
            consentCard.Permissions = "read::alexa:device:all:address";

            // Create the Simple card content.
            SimpleCard card = new SimpleCard();
            card.Title = String.Format("SessionSpeechlet - {0}", title);
            card.Subtitle = String.Format("SessionSpeechlet - Sub Title");
            card.Content = String.Format("SessionSpeechlet - {0}", outPutCard);

            // Create the SSML text output.
            SsmlOutputSpeech speech = new SsmlOutputSpeech();
            speech.Ssml = output;

            // Create the speechlet response.
            SpeechletResponse response = new SpeechletResponse();
            response.ShouldEndSession = shouldEndSession;
            response.OutputSpeech = speech;
            response.Card = card;

            if (!String.IsNullOrEmpty(repromptText))
            {
                PlainTextOutputSpeech speech2 = new PlainTextOutputSpeech();
                speech2.Text = repromptText;
                Reprompt reprompt = new Reprompt();
                reprompt.OutputSpeech = speech2;
                response.Reprompt = reprompt;
            }
            return response;
        }

**Comment by ElvenMonky** [comment]
When your skill needs user address, it sends request to the [Device Address API](https://developer.amazon.com/docs/custom-skills/device-address-api.html#getAddress). If response code is 403 Forbidden, you need to send `AskForPermissionsConsentCard` to the user with **list of** required permissions. You don't need to include OutputSpeech or any other attributes to the response with `AskForPermissionsConsentCard`. Also:
> The permissions value will always match the scope that you declared for the skill on the Configuration page in the Amazon Developer Portal.

So, your code will be something like below:
```
if (askForPermissions) { 
var consentCard = new AskForPermissionsConsentCard();
consentCard.Permissions = new[] { "read::alexa:device:all:address" };
return new SpeechletResponse { Card = consentCard };
} else {
...
```

**Comment by petersantiago** [comment]
Thank you very much!!!
