### ISSUE TITLE
VideoApp Response nested in SpeechletResponse?

### ISSUE THREAD

**Issue by bkolo** [AreYouFreeBusy/AlexaSkillsKit.NET#74]
An example response for videoApp directive on amazon docs looks like:

`{
  "version": "1.0",
  "sessionAttributes": null,
  "response": {
    "outputSpeech": null,
    "card": null,
    "directives": [
      {
        "type": "VideoApp.Launch",
        "videoItem": {
          "source": "https://www.example.com/video/sample-video-1.mp4",
          "metadata": {
            "title": "Title for Sample Video",
            "subtitle": "Secondary Title for Sample Video"
          }
        }
      }
    ],
    "reprompt": null
  }
}`

Is there another way to return directives so they are not nested inside a SpeechletResponse? 
This is the output that is getting generated.

`{
	"version": "1.0",
	"response": {
		"speechletResponse": {
			"directives": [{
				"videoItem": {
					"source": "https://www.example.com/video/sample-video-1.mp4",
					    "title": "Title for Sample Video",
						"subtitle": "Secondary Title for Sample Video"
					}
				}
			}
			]
		}
	},
	"sessionAttributes": null
}
`

**Comment by ElvenMonky** [comment]
Same issue was already reported in #70. The output you are getting is strange and doesn't seem to be possible using this library.
Could you provide complete code sample reproducing an issue?

**Comment by bkolo** [comment]
Well it looks like something is happening between my service and amazon that is altering my response.  I must have some kind of configuration issue with the app.

My Response from the server is:

`{
    "response": {
        "directives": [
            {
                "videoItem": {
                    "source": "https://video.internetvideoarchive.net/video.mp4?cmd=6&fmt=4&customerid=69249&publishedid=237393&e=1522934800&videokbrate=750&h=7c6e1603311ced87cb1be833f4fc1b75",
                    "metadata": {
                        "title": "The Matrix (Clean Trailer)"
                    }
                },
                "type": "VideoApp.Launch"
            }
        ]
    },
    "sessionAttributes": null
    },
    "version": "1.0"
}`

When using the alexa console, this is getting translated to:

`{
  "version": "1.0",
  "response": {
    "speechletResponse": {
      "directives": [
        {
          "videoItem": {
            "source": "https://video.internetvideoarchive.net/video.mp4?cmd=6&fmt=4&customerid=69249&publishedid=384742&e=1522938851&videokbrate=750&h=fcaffb6bf7c807767fb1d1949cc28a8c",
            "metadata": {
              "title": "Jaws (Clean Trailer)"
            }
          }
        },
        {
          "template": {
            "title": {
              "richText": "<big>The Video Detective</big>"
            },
            "backButtonBehavior": "VISIBLE"
          }
        }
      ]
    }
  },
  "sessionAttributes": null
  }
}`
