### ISSUE TITLE
InvalidSignature, NoContent 

### ISSUE THREAD

**Issue by trivedimehulk** [AreYouFreeBusy/AlexaSkillsKit.NET#76]
Hi there

I am novoice to using this library. For my Alexa app, I have the backend on Azure Webapi. When I wrapped my controller using this library, I am getting error "Validation result: InvalidSignature, NoContent ".

Can someone guide me what am I doing wrong? Do I need to install the cert somewhere OR what?

Any help is appreciated.

Thank you

**Comment by stefann42** [comment]
Here are some tutorials:
http://code-coverage.net/building-amazon-alexa-skills-with-net/
https://blog.terribledev.io/Making-alexa-skills-in-net/
