### ISSUE TITLE
Question : Using Dialogs

### ISSUE THREAD

**Issue by anandmukundan** [AreYouFreeBusy/AlexaSkillsKit.NET#80]
Is there any simple sample for how to use the new Dialog directives that are now available? The Azure Function sample seems to not use the Directives.Dialog, but rather a local implementation.

Thanks

**Comment by ElvenMonky** [comment]
Azure function sample uses directives from `AlexaSkillsKit.Interfaces.Dialog.Directives` namespace. It does so through `SpeechletResponseBuilder` and its extensions. The magic happens in 
[SpeechletResponseBuilderDialogExtentions.cs](https://github.com/AreYouFreeBusy/AlexaSkillsKit.NET/blob/master/AlexaSkillsKit.Sample.Dialog.AzureFunc/Helpers/Builder/SpeechletResponseBuilderDialogExtentions.cs) and [SpeechletResponseBuilder.cs](https://github.com/AreYouFreeBusy/AlexaSkillsKit.NET/blob/master/AlexaSkillsKit.Sample.Dialog.AzureFunc/Helpers/Builder/SpeechletResponseBuilder.cs)

**Comment by anandmukundan** [comment]
Thanks Elven, I will take a look at those code files...
