### ISSUE TITLE
Resolutions

### ISSUE THREAD

**Issue by theinternetguru2** [AreYouFreeBusy/AlexaSkillsKit.NET#81]
I can't figure out how to get to the values in the resolutions object to handle entity resolution. Is this functional in the skills kit? Does someone have a code sample?

**Comment by ElvenMonky** [comment]
It's true that there is no development activity on this library. However, resolutions should work. What was your issue exactly?

**Comment by ElvenMonky** [comment]
[JsonIgnore] is used to prevent Resolutions from being returned to Alexa (e.g. Slot from Request can be reused in Response when handling dialogs). It doesn't prevent Resolutions from appearing in Request Slots.

Probably, resolutions are missing from the json body of the request your skill receives. One of the possible reasons might be that device language doesn't match the region of your account, as described here: https://forums.developer.amazon.com/answers/87868/view.html

**Comment by ElvenMonky** [comment]
I assume this was resolved. Closing for now. Feel free to reopen if you still see an issue
