### ISSUE TITLE
Slot values are empty

### ISSUE THREAD

**Issue by chmasi** [AreYouFreeBusy/AlexaSkillsKit.NET#90]
Dear All

since a cuple of days the values of the slots defined in the skill stays empty, any suggestion? was there a change on Amazon?

Martin

**Comment by ElvenMonky** [comment]
Did you test your skill with [Developer Console](https://developer.amazon.com/en-US/docs/alexa/devconsole/test-your-skill.html#test-simulator)? If so, is the behavior you see when in developer console the same as when making real requests?

Can you provide more information about the issue you see and your use case?
Also can you tell more your usage of the library, do you use version released to NuGet or forked this repository?
We have few changes merged recently to repository, but not deployed new version to NuGet.

**Comment by chmasi** [comment]
This is my request:

I am using the lates NUGET 1.6 Version.

I have removed  access token. user id, etc out of this request.
`
{
	"version": "1.0",
	"session": {
		"new": true,
		"sessionId": "amzn1.echo-api.session.732fb7ec-77bd-477d-b53a-6e515c6225f2",
		"application": {
			"applicationId": "amzn1.ask.skill.5786bdf8-7eb5-4f3a-8eb6-366e3c407ded"
		},
		"user": {
			"userId": 
		}
	},
	"context": {
		"Viewports": [
			{
				"type": "APL",
				"id": "main",
				"shape": "RECTANGLE",
				"dpi": 160,
				"presentationType": "STANDARD",
				"canRotate": false,
				"configuration": {
					"current": {
						"video": {
							"codecs": [
								"H_264_42",
								"H_264_41"
							]
						},
						"size": {
							"type": "DISCRETE",
							"pixelWidth": 1024,
							"pixelHeight": 600
						}
					}
				}
			}
		],
		"Viewport": {
			"experiences": [
				{
					"arcMinuteWidth": 246,
					"arcMinuteHeight": 144,
					"canRotate": false,
					"canResize": false
				}
			],
			"shape": "RECTANGLE",
			"pixelWidth": 1024,
			"pixelHeight": 600,
			"dpi": 160,
			"currentPixelWidth": 1024,
			"currentPixelHeight": 600,
			"touch": [
				"SINGLE"
			],
			"video": {
				"codecs": [
					"H_264_42",
					"H_264_41"
				]
			}
		},
		"System": {
			"application": {
				"applicationId": "amzn1.ask.skill.5786bdf8-7eb5-4f3a-8eb6-366e3c407ded"
			},
			"user": {
				"userId": "amzn1.ask.account.AHNUFGGTEPHRJIK4M6VMPVEBTSJJGQX3UONI3T2AYUIT6RKOQDLBKVKO5TUEKU3ODQXM4T4MYH7BUDGU25RIVUI2BYLOKAQLZUQUKQZDK4BYWN3ZUXVQI7OUTNZINOBV5H6ZXSOEHEYCYDKYS5RC4LNO3O6BTCFSGTY4CFOGAAU4DYU4MRY3F4LEP2EFGR6HOJWW7IHUYQZ2SNQ"
			},
			"device": {
				"deviceId": 
				"supportedInterfaces": {}
			},
			"apiEndpoint": "https://api.eu.amazonalexa.com",
			"apiAccessToken": 
		}
	},
	"request": {
		"type": "IntentRequest",
		"requestId": "amzn1.echo-api.request.209bae9f-d43c-4260-83b8-71c364fa1066",
		"locale": "de-DE",
		"timestamp": "2020-09-13T05:15:42Z",
		"intent": {
			"name": "SolarAnlage",
			"confirmationStatus": "NONE",
			"slots": {
				"questions": {
					"name": "questions",
					"resolutions": {
						"resolutionsPerAuthority": [
							{
								"authority": "amzn1.er-authority.echo-sdk.amzn1.ask.skill.5786bdf8-7eb5-4f3a-8eb6-366e3c407ded.questions",
								"status": {
									"code": "ER_SUCCESS_MATCH"
								},
								"values": [
									{
										"value": {
											"name": "Status",
											"id": "ec53a8c4f07baed5d8825072c89799be"
										}
									}
								]
							}
						]
					},
					"confirmationStatus": "NONE",
					"source": "USER"
				}
			}
		}
	}
}
`
as you can see my slot is questions and the value is status, this was working since 2 years now. 

Current Situation:
after handling the request 

`string name = nameSlot.Value;`

this value stays emty but should contain "Status"

Cheers
Martin

**Comment by ElvenMonky** [comment]
Ok, I can only see one slot in your request named "questions" and it doesn't have clearly resolved value. I presume Alexa doesn't have confidence in what value slot should have.
You could verify if anything changed in your slot's configuration in Alexa Skill Builder.

Request above does however have some value inside resolutions, that you can access something like:
`string name = intent.Slots["questions"].Resolutions.ResolutionsPerAuthority[0].Values[0].Value.Name`

**Comment by chmasi** [comment]
Hi,

as I wrote above, it was working since 2 years, I did not change anything, it stops working out of the blue.

Martin

**Comment by ElvenMonky** [comment]
Gotcha. Yeah, clearly request that you shared doesn't contain what you expect it to have. So something must have happened with Alexa before Skill receives a request and this library comes into play.

If nobody here knows answer you are looking for, you might need to contact Alexa support or do your own investigation in Developer Console.
I'll leave this open to see if others started to face any issues with their skills too.

**Comment by chmasi** [comment]
Thanks, 
I have one last question you are writing that " I can only see one slot in your request named "questions" and it doesn't have clearly resolved value"

what do you mean it does not have a resolved value, can you give me an example how it should look like from your point of view.

Cheers
Martin

**Comment by ElvenMonky** [comment]
Sure, below is the "intent" part of the request. I added missing value in bold:

"intent": { "name": "SolarAnlage", "confirmationStatus": "NONE", "slots": { "questions": { "name": "questions", **value: "Status",** "resolutions": { "resolutionsPerAuthority": [ { "authority": "amzn1.er-authority.echo-sdk.amzn1.ask.skill.5786bdf8-7eb5-4f3a-8eb6-366e3c407ded.questions", "status": { "code": "ER_SUCCESS_MATCH" }, "values": [ { "value": { "name": "Status", "id": "ec53a8c4f07baed5d8825072c89799be" } } ] } ] }, "confirmationStatus": "NONE", "source": "USER" } } }

**Comment by chmasi** [comment]
Thanky you, 
this looks like something would not be ok with the Skill? Maybe you can have a look on the model, is there anything wrong?

{
    "interactionModel": {
        "languageModel": {
            "invocationName": "my reserve",
            "modelConfiguration": {
                "fallbackIntentSensitivity": {
                    "level": "LOW"
                }
            },
            "intents": [
                {
                    "name": "AMAZON.CancelIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.HelpIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.StopIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.NavigateHomeIntent",
                    "samples": []
                },
                {
                    "name": "AMAZON.FallbackIntent",
                    "samples": []
                },
                {
                    "name": "SolarAnlage",
                    "slots": [
                        {
                            "name": "questions",
                            "type": "questions"
                        }
                    ],
                    "samples": [
                        "wie ist die Ladung der {questions}",
                        "frag my reserve nach der {questions} ladung",
                        "frag my reserve nach dem status der {questions}",
                        "wie ist der {questions} von my reserve",
                        "frag my reserve nach dem aktuellen {questions}",
                        "frag my reserve ob ich den {questions} einschalten kann",
                        "frag my reserve ob ich die {questions} einschalten kann",
                        "frag my reserve ob ich strom {questions} kann",
                        "frag my reserve nach dem {questions}"
                    ]
                }
            ],
            "types": [
                {
                    "name": "questions",
                    "values": [
                        {
                            "name": {
                                "value": "Ladung"
                            }
                        },
                        {
                            "name": {
                                "value": "Batterie",
                                "synonyms": [
                                    "Batterieladung"
                                ]
                            }
                        },
                        {
                            "name": {
                                "value": "Verbraten"
                            }
                        },
                        {
                            "name": {
                                "value": "Trockner"
                            }
                        },
                        {
                            "name": {
                                "value": "Spülmaschine"
                            }
                        },
                        {
                            "name": {
                                "value": "Status"
                            }
                        }
                    ]
                }
            ]
        }
    }
}

**Comment by ElvenMonky** [comment]
Your model look good to me. You can try to add IDs to slot values or look at other suggestions on stackoverflow, e.g.: https://stackoverflow.com/questions/42721603/alexa-custom-slot-type-no-value-in-intent

**Comment by ElvenMonky** [comment]
@chmasi Have you been able to resolve your issue since? I'll go ahead and close this issue. Feel free to reopen if you still need help on this.
